title: WatInside
author:
  name: WatInside
  email: support@watinside.com
description: >-
  WatInside is a smart storage organization app that helps you find your things, faster.
  Scan handwritten or printed labels with our AI-powered app and instantly see what’s inside your boxes.
  Never forget what’s in your boxes again.
baseurl: ""
url: "https://watinside.com"
twitter_username: watinside
github_username: watinside

theme: minima

plugins:
  - jekyll-feed